<!-- TWEETER -->

<a href="https://twitter.com/share" class="twitter-share-button" data-size="large" data-count="none">asd</a>
<script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>




<!-- GOOGLE -->

<!-- Umieść ten tag w miejscu, w którym chcesz wygenerować przycisk +1. -->
<div class="g-plusone" data-annotation="none"></div>

<!-- Umieść to wywołanie generujące w odpowiednim miejscu. -->
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>



<!-- FACEBOOK -->
<div id="fb-root"></div>

<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=293030094054954";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div style="width:48px;">
    <div class="fb-like" data-href="greenlight-dev" data-send="false" data-layout="button_count" data-width="10" data-show-faces="true" data-font="arial"></div>
</div>
