
<div class="footer-container">
    <div class="footer">
        <div class="out">
            <div class="in">
                <div class="payment-methods"></div>
                <div class="security-certificates"></div>
            </div>
        </div>               
        <address><span><?php echo $this->getCopyright() ?></span></address>
        <?php //echo $this->getChildHtml() ?>        
    </div>
</div>
<script type="text/javascript">

$$('#shopping-cart-table tbody tr').each(function(o){
   
   var paddingTop = parseInt(o.select('td').first().getStyle('padding-top'));
   var paddingBottom = parseInt(o.select('td').first().getStyle('padding-bottom'));

   var containerHeight = o.getHeight() - paddingTop - paddingBottom; 
 
    o.select('div.with-border').each(function(e){
       e.setStyle({
           borderRight: '1px solid #d5e3ec', 
           height: containerHeight+"px",
           lineHeight: containerHeight+"px"
       })
   });
     
});


</script>


