
<div class="footer-container">
    <div class="footer">
        <div class="out">
            <div class="in">
                <div class="payment-methods"></div>
                <div class="security-certificates"></div>
            </div>
        </div>               
        <address><span><?php echo $this->getCopyright() ?></span></address>
        <?php //echo $this->getChildHtml() ?>        
    </div>
</div>



