<?php $currentUrl = Mage::helper('core/url')->getCurrentUrl(); ?>

<div class="header-container">
    <div class="header">
        <div class="quick-access">
            <?php //echo $this->getChildHtml('topSearch') ?>
<!--            <p class="welcome-msg"><?php //echo $this->getWelcome()        ?> <?php echo $this->getAdditionalHtml() ?></p>-->

            <?php echo $this->getChildHtml('topLinks') ?>
            <?php echo $this->getChildHtml('store_language') ?>                     
        </div>
        <?php if ($this->getIsHomePage()): ?>
            <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
        <?php else: ?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
        <?php endif ?>
        <?php echo $this->getChildHtml('topCart'); ?>            
        <?php echo $this->getChildHtml('topContainer'); ?>    
        <div class="top-menu">
            <div class="l">
                <div class="r">
                    <div class="m">
                        <ul class="menu">
                            <?php $home = (Mage::getSingleton('cms/page')->getIdentifier() == 'home' && Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms') ? 'active' : '' ?>
                            <li class="first"><a href="<?php echo $this->getUrl('') ?>" class="<?php echo $home ?>"><span><span><span><?php echo __('Products') ?></span></span></span></a></li>
                            <?php $brands = (strstr($currentUrl, $this->getUrl('brands'))) ? 'active' : '' ?>
                            <li><a href="<?php echo $this->getUrl('brands-list') ?>" class="<?php echo $brands ?>"><span><span><span><?php echo __('Brands') ?></span></span></span></a></li>
                            <?php $room = (strstr($currentUrl, $this->getUrl('room-list'))) ? 'active' : '' ?>
                            <li><a href="<?php echo $this->getUrl('room-list') ?>" class="<?php echo $room ?>"><span><span><span><?php echo __('Room') ?></span></span></span></a></li>
                            <?php $gagets = (strstr($currentUrl, $this->getUrl('gagets'))) ? 'active' : '' ?>
                            <li><a href="<?php echo $this->getUrl('gagets') ?>" class="<?php echo $gagets ?>"><span><span><span><?php echo __('Gadgets') ?></span></span></span></a></li>
                            <?php $sales = (strstr($currentUrl, $this->getUrl('sales'))) ? 'active' : '' ?>
                            <li><a href="<?php echo $this->getUrl('sales') ?>" class="<?php echo $sales ?>"><span><span><span><?php echo __('Sales') ?></span></span></span></a></li>
                            <?php $guaranties = (strstr($currentUrl, $this->getUrl('guaranties'))) ? 'active' : '' ?>
                            <li><a href="<?php echo $this->getUrl('guaranties') ?>" class="<?php echo $guaranties ?>"><span><span><span><?php echo __('Guaranties') ?></span></span></span></a></li>
                            <?php $blog = (strstr($currentUrl, $this->getUrl('blog'))) ? 'active' : '' ?>
                            <li><a href="<?php echo $this->getUrl('blog') ?>" class="<?php echo $blog ?>"><span><span><span><?php echo __('Blog') ?></span></span></span></a></li>
                            <?php $newsletter = (strstr($currentUrl, $this->getUrl('newsletter'))) ? 'active' : '' ?>
                            <li><a href="<?php echo $this->getUrl('newsletter') ?>" class="<?php echo $newsletter ?>"><span><span><span><?php echo __('Newsletter') ?></span></span></span></a></li>
                            <?php $faq = (strstr($currentUrl, $this->getUrl('faq'))) ? 'active' : '' ?>
                            <li><a href="<?php echo $this->getUrl('faq') ?>" class="<?php echo $faq ?>"><span><span><span><?php echo __('F.a.q.') ?></span></span></span></a></li>
                            <?php $about = (strstr($currentUrl, $this->getUrl('about'))) ? 'active' : '' ?>
                            <li><a href="<?php echo $this->getUrl('about') ?>" class="<?php echo $about ?>"><span><span><span><?php echo __('About us') ?></span></span></span></a></li>                          
                            <?php $contact = (strstr($currentUrl, $this->getUrl('contacts'))) ? 'active' : '' ?>
                            <li class="last"><a href="<?php echo $this->getUrl('contacts') ?>" class="<?php echo $contact ?>"><span><span><span><?php echo __('Contact') ?></span></span></span></a></li>
                        </ul>
                        <div class="sub-menu">                            
                            <?php
                            if(Mage::getSingleton('cms/page')->getIdentifier() == 'home'  && Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms'){
                                echo $this->getChildHtml('topMenu');
                            }
                            ?>
                            <?php echo $this->getChildHtml('topSearch') ?>    
                        </div>
                        <div class="clear"><!-- --></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

