<div class="header-container">
    <div class="header">
        <div class="quick-access">
            <?php //echo $this->getChildHtml('topSearch') ?>
<!--            <p class="welcome-msg"><?php //echo $this->getWelcome()      ?> <?php echo $this->getAdditionalHtml() ?></p>-->
  
<?php echo $this->getChildHtml('store_language') ?>        
 <?php echo $this->getChildHtml('topLinks') ?>
                   
        </div>        
        <?php if ($this->getIsHomePage()): ?>
            <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
        <?php else: ?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
        <?php endif ?>
        <?php echo $this->getChildHtml('topCart'); ?>            
        <?php echo $this->getChildHtml('topContainer'); ?>    
        <?php //echo $this->getChildHtml('topMenu') ?>
        <div class="top-menu">
            <div class="l">
                <div class="r">
                    <div class="m">
                        <ul class="menu">
                            <li class="first"><a href="#" class="active"><span><span><span>PRODUCTS</span></span></span></a></li>
                            <li><a href="brands-list"><span><span><span>BRANDS</span></span></span></a></li>
                            <li><a href="room-list"><span><span><span>ROOM</span></span></span></a></li>
                            <li><a href="#"><span><span><span>GAGETS</span></span></span></a></li>
                            <li><a href="#"><span><span><span>SALES</span></span></span></a></li>
                            <li><a href="#"><span><span><span>GUARANTIES</span></span></span></a></li>
                            <li><a href="#"><span><span><span>BLOG</span></span></span></a></li>
                            <li><a href="#"><span><span><span>NEWSLETTER</span></span></span></a></li>
                            <li><a href="#"><span><span><span>F.A.Q.</span></span></span></a></li>
                            <li><a href="#"><span><span><span>ABOUT US</span></span></span></a></li>
                            <li class="last"><a href="#"><span><span><span>CONTACT</span></span></span></a></li>
                        </ul>
                        <div class="sub-menu">
                            <?php echo $this->getChildHtml('topSearch') ?>    
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

</div>

