<div class="home-page">
    <div class="block-content">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_page_banner_rotator')->toHtml() ?> 
    </div>
    <div class="col-left">
        <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setName('home.newsletter')->setTemplate('newsletter/subscribe.phtml')->toHtml() ?>
        <?php echo $this->getLayout()->createBlock('testimonial/testimonial')->setName('home.testimonial')->setTemplate('testimonial/testimonials_box.phtml')->toHtml() ?>
    </div>
    <div class="col-main">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_page_brands_rotator')->setTemplate('cms/widget/static_block/default.phtml')->toHtml() ?>
        
        <?php echo  $this->getLayout()->createBlock('reports/product_viewed')->setTemplate('products/small_view_recently_viewed.phtml')->setAttribute('title', 'RECENTLY VIEWED PRODUCTS')->toHtml() ?>
        <?php //echo $this->getLayout()->createBlock('products/bestselling')->setTemplate('products/small_view.phtml')->setAttribute('title', 'BESTSELLING PRODUCTS')->toHtml() ?>
        <?php echo $this->getLayout()->createBlock('products/new')->setTemplate('products/small_view.phtml')->setAttribute('title', 'NEW ARRIVIALS')->toHtml() ?>
    </div>
</div>
