<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_inquiries = $this->getInquiries(); ?>
<div class="page-title">
    <h1><?php echo $this->__('My Inquiries') ?></h1>
</div>
<?php echo $this->getPagerHtml(); ?>

<table class="data-table" id="my-inquiries-table">
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th><?php echo $this->__('Inquiry #') ?></th>
            <th><?php echo $this->__('Date') ?></th>
            <th><span class="nobr"><?php echo $this->__('Status') ?></span></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($_inquiries as $_inquiry): ?>
            <tr>
                <td><?php echo sprintf("%08d", $_inquiry->getId()); ?></td>
                <td><?php echo $this->formatDate($_inquiry->getCreatedTime()) ?></td>
                <td><?php echo ($this->helper('offer/inquiry')->canSubmitt($_inquiry)) ? $this->__('new') : $this->__('submitted'); ?></td>
                <td class="a-center">
                    <span class="nobr"><a href="<?php echo $this->getViewUrl($_inquiry) ?>"><?php echo $this->__('View Inquiry') ?></a>
                        <?php if ($this->helper('offer/inquiry')->canSubmitt($_inquiry)) : ?>
                            <span class="separator">|</span> <a href="<?php echo $this->getSendUrl($_inquiry) ?>" class="link-reorder"><?php echo $this->__('Submitt') ?></a>
                        <?php endif ?>
                    </span>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>