<form id="form-validate" method="post" action="<?php echo $this->getUrl('rewardpoints/rewardpoints/send')?>">
    <div class="fieldset group-select">
        <?php echo $this->getBlockHtml('formkey')?>
        <div class="box-head"><h2><?php echo $this->__('Send Reward Points To Friend') ?></h2></div>
        <ul class="form-list">
            <li class="fields">
                <div class="customer-name">
                	<?php $addonClass="";?>
                	<?php if(version_compare(Mage::getVersion(),"1.3.2.4","<=")) $addonClass = " input-box";?>
				    <div class="field<?php echo $addonClass;?> name-firstname">
				        <label class="required" style="color:#666666" for="email"><?php echo Mage::helper('rewardpoints')->__('Email of your friend');?><em style="color:#EB340A">*</em></label>
				        <div class="input-box">
				            <input type="text" class="input-text required-entry validate-email" title="Email" name="email" id="email" gtbfieldid="135">
				        </div>
				    </div>
				    <div class="field<?php echo $addonClass;?> name-firstname">
				        <label class="required" style="color:#666666" for="name"><?php echo Mage::helper('rewardpoints')->__('Friend name');?><em style="color:#EB340A">*</em></label>
				        <div class="input-box">
				            <input type="text" class="input-text required-entry" title="Name" name="name" id="name" gtbfieldid="135">
				        </div>
				    </div>
				</div>
            </li>
           
            <li>
			    <div class="validate-code">
			        <div class="field<?php echo $addonClass;?> name-firstname">
			        	<label class="required" style="color:#666666" for="amount"><?php echo Mage::helper('rewardpoints')->__('Amount');?><em style="color:#EB340A">*</em></label>
			        	<div class="input-box"><input type="text" class="input-text required-entry validate-digits" title="Amount" name="amount" id="amount" gtbfieldid="136"></div>
			        </div>
			         <?php if(Mage::helper('rewardpoints')->enabledCapcha()):?>
			        <div class="field<?php echo $addonClass;?> name-firstname" style="width:300px; margin-top: 10px;">
			        	<img id="siimage" align="left" style="border: 1px solid #B6B6B6;" src="<?php echo trim($this->getUrl('rewardpoints/rewardpoints/image'),"/")."?sid=".time(); ?>" />
       					<a tabindex="-1" style="border-style: none;" href="#" title="Refresh Image" onclick="document.getElementById('siimage').src = '<?php echo trim($this->getUrl('rewardpoints/rewardpoints/image'),"/"); ?>?sid=' + Math.random(); return false"><img src="<?php echo $this->getSkinUrl('mw_rewardpoints/images/refresh.gif')?>" alt="Reload Image" border="0" onclick="this.blur()" align="bottom" /></a>
       					<label class="required" style="color:#666666" for="capcha"><?php echo Mage::helper('rewardpoints')->__('Security Code');?><em style="color:#EB340A">*</em></label>
			        	<div class="input-box"><input type="text" class="input-text required-entry" title="Validate Code" name="code" id="capcha" gtbfieldid="136"></div>
			        </div>
			        <?php endif;?>
			    </div>
            </li>
            <li>
                <div>
			        <button class="button form-button" title="<?php echo Mage::helper('rewardpoints')->__("Send");?>" type="submit"><span><span>  <?php echo Mage::helper('rewardpoints')->__("Send");?>  </span></span></button>
			        <p class="required"><?php echo Mage::helper('rewardpoints')->__("* Required Fields");?></p>
			    </div>
            </li>
        </ul>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    //]]>
</script>
