<div class="cart">
    <?php $_cartQty = $this->getSummaryCount() ?>
    <a href="#"></a>
    <div>
        <span>
            <?php echo $this->__('Shopping Cart') ?>: 
            <?php echo ($_cartQty > 0) ? $_cartQty : 0 ?> 
            <?php echo $this->__('Item(s)') ?>
        </span>
    </div>
    <div>
        <span class="price">
            <?php
            if (($_cartQty > 0)) {
                $_subtotalInclTax = $this->getSubtotalInclTax();
                echo ($_subtotalInclTax) ? Mage::helper('checkout')->formatPrice($_subtotalInclTax) : Mage::helper('checkout')->formatPrice($this->getSubtotal());
            }
            else {
                echo Mage::helper('checkout')->formatPrice();
            }
            ?>
        </span>
    </div>
</div>
