<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php echo $this->getDocType() ?>
<rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
>
<channel>
	<title><?php echo $this->__('Comments on: %s', $this->getPost()->getPostTitle()) ?></title>
	<atom:link href="<?php echo $this->getPost()->getCommentFeedUrl() ?>" rel="self" type="application/rss+xml" />
	<link><?php echo $this->getPost()->getPermalink() ?></link>
	<description><![CDATA[<?php echo $this->getBlogName() ?>]]></description>
	<lastBuildDate><?php echo date('D, d M Y H:i:s +0000') ?></lastBuildDate>
	<language><?php echo $this->getRssLanguage() ?></language>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>http://fishpig.co.uk/wordpress-integration/</generator>
	<?php $comments = $this->getComments() ?>
	<?php foreach($comments as $comment): ?>
	<item>
		<title><![CDATA[<?php echo $this->__('By: %s', $comment->getCommentAuthor()) ?>]]></title>
		<link><?php echo $comment->getUrl() ?></link>
		<dc:creator><![CDATA[<?php echo $comment->getCommentAuthor() ?>]]></dc:creator>
		<pubDate><?php echo $comment->getCommentDate('D, d M Y H:i:s +0000') ?></pubDate>
		<guid isPermaLink="false"><?php echo $comment->getGuid() ?></guid>
		<description><![CDATA[<?php echo $comment->getCommentContent() ?>]]></description>
		<content:encoded><![CDATA[<?php echo $comment->getCommentContent() ?>]]></content:encoded>
	</item>
	<?php endforeach; ?>
</channel>
</rss>