<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $comments = $this->getComments() ?>
<?php if (count($comments) > 0): ?>
	<div class="block block-blog block-blog-comments">
		<?php if ($title = $this->getTitle()): ?>
			<div class="block-title">
				<strong><span><?php echo $this->__($title) ?></span></strong>
			</div>
		<?php endif; ?>
		<div class="block-content">
			<ul id="wp-recent-comments-list">
				<?php foreach($comments as $comment): ?>
					<li class="item">
						<a href="<?php echo $comment->getUrl() ?>" title="<?php echo $comment->getName() ?>">
							<?php echo $this->__('%s on \'%s\'', $comment->getCommentAuthor(), $comment->getPost()->getPostTitle()) ?>
						</a>
					</li>
				<?php endforeach; ?>
			</ul>
			<script type="text/javascript">decorateList('wp-recent-comments-list')</script>
		</div>
	</div>
<?php endif; ?>