<?php if ($product = $this->getProductForBuying()):?>
<li>
    <fieldset class="add-to-cart">
        <form action="<?php echo $this->getAddToCartUrl($product) ?>" method="post" id="product_addtocart_form">
            <span class="qty">
                <label><?php echo $this->__('Qty of Store Balance units:')?></label>
                <input name="qty" type="text" class="input-text qty" id="qty" maxlength="12" value="<?php echo $this->getMinimalQty($product) ?>" /></span>
            </span>
            <?php if ($this->showButton('add')) :?>
            <button class="button" onclick="productAddToCartForm.submit('<?php echo $this->getAddToCartUrl($product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
            <?php endif?>
            <?php if ($this->showButton()): ?>
            <div class="left separator"><?php echo $this->__('or');?></div>
            <?php endif?>
            <?php if ($this->showButton('purchase')) :?>
            <button class="button" onclick="productAddToCartForm.submit('<?php echo $this->getPurchaseUrl($product) ?>')"><span><?php echo $this->__('Proceed to Checkout') ?></span></button>
            <?php endif?>
        </form>
    </fieldset>
    <script type="text/javascript">
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(actionUrl){
                if (this.validator.validate()) {
                	this.form.action = actionUrl;
                    this.form.submit();
                }
        }.bind(productAddToCartForm);
    </script>
</li>
<?php endif; ?>