<?php
/**
 *
 *
 */
?>
<div class="content-header">
    <h3 class="icon-head head-adminhtml-support"><?php echo $this->__("FishPig's WordPress Integration") ?></h3>
</div>
<p style="font-size:18px; text-align: center;">
	<?php echo $this->__("If you're having problems with WordPress Integration and want some help, you can email FishPig directly at <a href=\"mailto:help@fishpig.co.uk\">help@fishpig.co.uk</a>.") ?><br />
	<?php echo $this->__('Alternatively, you can find help in the extension\'s <a href="http://fishpig.co.uk/wordpress-integration/" target="_wp">documentation</a>.') ?>	
</p>