<?php  if ($this->getTarget() == "community" && !Mage::helper('relatedproducts')->isEnterprise()): ?>
<?php if($this->getEnabled() && count($this->getRelatedProductsCollection())): ?>
<div class="aw-box aw-base-mini aw-mini-related-items block">
    <div class="head">
        <h4><?php echo $this->__('Customers Who Bought This Also Bought') ?></h4>
    </div>
    <div class="aw-content" <?php if (Mage::helper('relatedproducts')->checkVersion('1.4.1.0')) { echo "id=\"after1400\""; }?>>
        <p><strong><?php echo $this->__('Check items to add to the cart or') ?>&nbsp;<a href="#" onclick="selectAllAwRelated(this);return false;"><?php echo $this->__('select all') ?></a></strong></p>
        <ol>
        <?php foreach($this->getRelatedProductsCollection() as $_item): ?>
        <li<?php if($_item->isComposite() || !$_item->isSaleable()): ?> class="super-products"<?php endif; ?>>
            <div class="product-images">
            <?php if(!$_item->isComposite() && $_item->isSaleable()): ?>
                <span class="checkbox-container">
                <?php if (!$_item->getRequiredOptions()): ?>
                    <input type="checkbox" class="aw-related-checkbox left" id="aw-related-checkbox<?php echo $_item->getId() ?>" name="aw_related_products[]" value="<?php echo $_item->getId() ?>" />
                <?php endif; ?>
                </span>
            <?php else: ?>
                <span class="checkbox-container">&nbsp;</span>
            <?php endif; ?>
                <a href="<?php echo $_item->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(50) ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" width="50" height="50" /></a>
            </div>
            <div class="product-details">
                    <a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a>
                    <?php echo $this->getPriceHtml($_item, true); ?>
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="aw-link-cart"><?php echo $this->__('Add to Wishlist') ?></a>
                    <?php endif; ?>
            </div>
        </li>
        <?php endforeach ?>
        </ol>
    </div>
</div>
<script type="text/javascript">
<!--
$$('.aw-related-checkbox').each(function(elem){
    Event.observe(elem, 'click', addAwRelatedToProduct)
});

var relatedAwProductsCheckFlag = false;
function selectAllAwRelated(txt){
    if (relatedAwProductsCheckFlag == false) {
        $$('.aw-related-checkbox').each(function(elem){
            elem.checked = true;
        });
        relatedAwProductsCheckFlag = true;
        txt.innerHTML="<?php echo $this->__('unselect all') ?>";
    } else {
        $$('.aw-related-checkbox').each(function(elem){
            elem.checked = false;
        });
        relatedAwProductsCheckFlag = false;
        txt.innerHTML="<?php echo $this->__('select all') ?>";
    }
    addAwRelatedToProduct();
}

function addAwRelatedToProduct(){
    var checkboxes = $$('.aw-related-checkbox');
    var values = [];
    for(var i=0;i<checkboxes.length;i++){
        if(checkboxes[i].checked) values.push(checkboxes[i].value);
    }
    
    if($('related-products-field')){
        $('related-products-field').value = values.join(',');
    }
    
}
//-->
</script>
<?php endif ?>
<?php endif ?>