<?php
/**
 *
 *
 */
?>
<div class="entry-edit left" style="width:49%;">
	<div class="entry-edit-head">
		<h4><?php echo $this->__('Support Tickets') ?></h4>
	</div>
	<fieldset class="config">
		<legend><?php echo $this->__('Support Tickets') ?></legend>
		<p>
			If you're struggling to install the module or can't quite achieve the configuration you desire, you can request support by clicking the button below.
		</p>
		<p>Before requesting support, please try and fix the problem yourself. In doing so, you may learn a little about how the module and Magento work.
		<p>&nbsp;</p>
		<p>
			<button type="button" id="submit-support-ticket"><span><?php echo $this->__('Create a Support Ticket') ?></span></button>
		</p>
	</fieldset>
</div>
<div class="entry-edit right" style="width:49%;">
	<div class="entry-edit-head">
		<h4><?php echo $this->__('Bug Reports') ?></h4>
	</div>
	<fieldset class="config">
		<legend><?php echo $this->__('Bug Reports') ?></legend>
		<p>
			Although the module has been tested, there are so many variables that it is impossible to test every single setup. This means that bugs often slip through the net into the live version. If you spot a bug or see something that just doesn't seem right, please let us know!
		</p>
		<p>&nbsp;</p>
		<p>
			<button type="button" id="submit-bug-report"><span><?php echo $this->__('Create a Bug Report') ?></span></button>
		</p>
	</fieldset>
</div>
<div style="clear:both;"></div>
