<div class="std testimonials_container">
    <h1 class="testimonials_title"><?php echo $this->__("Testimonials"); ?></h1>
    <div class="testimonials">
    <?php $collection = Mage::getModel("testimonial/testimonial")->getCollection(); ?>
    <?php $collection->setOrder('testimonial_position', 'ASC'); ?> 
    <?php $testimonials = $collection->load(); ?>
    <?php $i = 0;?>
    <?php if ($testimonials->count() > 0): ?>
    <?php   foreach ($testimonials as $testimonial): ?>
	<div class="testimonial_<?php $i++; echo (is_int($i/2) ? "r" : "l")?>">
	    <?php if ($testimonial->getTestimonialImg()): ?>
	    <div class="testimonial_image"><img alt="<?php echo $testimonial->getTestimonialName(); ?>" src="<?php echo Mage::getUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). $testimonial->getTestimonialImg() ?>" /></div>
	    <?php endif; ?>
	    <div class="testimonial_text"><?php echo $testimonial->getTestimonialText(); ?>
		<h2><?php echo $testimonial->getTestimonialName(); ?></h2>
	    </div>
	</div>
    <?php   endforeach; ?>

    <?php endif;?>

    </div>
</div>
