<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $products = $this->getProducts() ?>
<?php if (count($products) > 0): ?>
	<div class="block block-blog block-associated-products">
		<?php if ($title = $this->getTitle()): ?>
			<div class="block-title">
				<strong><?php echo $title ?></strong>
			</div>
		<?php endif; ?>
		<div class="block-content">
			<ul id="wp-associated-product-list">
				<?php foreach($products as $product): ?>
					<li class="item">
						<a href="<?php echo $product->getProductUrl() ?>">
							<?php echo $product->getName() ?>
						</a>
					</li>
				<?php endforeach; ?>
			</ul>
		</div>
		<script type="text/javascript">decorateList('wp-associated-product-list');</script>
	</div>
<?php endif; ?>