<?php
/**
 *
 *
 */
?>
<div class="entry-edit left" style="width:49%;">
	<div class="entry-edit-head">
		<h4>Submit your <span class="enquirytype"><?php echo $this->__('Support Ticket') ?></span></h4>
	</div>
	<fieldset class="config">
		<legend>Submit your <span class="enquirytype"><?php echo $this->__('Support Ticket ') ?></span></legend>
		<p>
			Click the button below to complete your <span class="enquirytype" style="text-transform:lower;">Support Ticket </span>. Please allow us 24 hours to respond to your message.
		</p>
		<p>&nbsp;</p>
		<p>
			<button type="button" onclick="editForm.submit();" class="scalable save"><span>Send your <span class="enquirytype" style="background:none !important;padding-left:0;"><?php echo $this->__('Support Ticket') ?></span></span></button>
		</p>
	</fieldset>
</div>
<div class="entry-edit right" style="width:49%;">
	<div class="entry-edit-head">
		<h4><?php echo $this->__('Having Trouble?') ?></h4>
	</div>
	<fieldset class="config">
		<legend><?php echo $this->__('Having Trouble?') ?></legend>
		<p><?php echo $this->__('If you\'re having trouble installing this extension, why not let us install for you? We created this extension so we know how to get it running just right.') ?></p>
		<p><?php echo $this->__('For more information about this service,') ?> <a href="http://fishpig.co.uk/wordpress-integration-setup/" title="<?php echo $this->__('FishPig\'s WordPress Integration Setup') ?>" target="_blank">click here</a>.</p>
	</fieldset>
</div>

<div style="clear:both;"></div>