<?php
/**
 *
 *
 */
?>
<div class="entry-edit">
	<div class="entry-edit-head">
		<h4><?php echo $this->__('Log Files') ?></h4>
	</div>
	<fieldset class="config">
		<legend><?php echo $this->__('Log Files') ?></legend>
		<?php $logs = $this->helper('wordpress/debug_environmentReport')->getLogEntries(30) ?>
		<?php if ($logs): ?>
			<p><?php echo nl2br(trim($logs)) ?></p>
		<?php else: ?>
			<p>No log files have been found. It is recommend that you enable logging before submitting this message as logs will help us a find a solution much more efficiently.</p>
			<p>&nbsp;</p>
		<?php endif; ?>
		<div style="height:1%;overflow:hidden;"><button type="button" class="scalable back left support-previous" id="content_previous"><span><?php echo $this->__('Previous') ?></span></button><button type="button" class="scalable add right support-next" id="content_next"><span><?php echo $this->__('Next') ?></span></button></div>
	</fieldset>
</div>

