<div class="discount">
        <h2><?php echo $this->__('Gift Gards'); ?></h2>
        <?php if (Mage::helper('customer')->isLoggedIn()) : ?>
        <div class="discount-form">
            <form method="post" action="<?php echo $this->getUrl('*/*/giftcardActive'); ?>" name="giftcardActive">
            <div class="input-box">
                <input type="checkbox" value="1" name="giftcard_use" id="giftcard_use" class="checkbox" onclick="document.forms['giftcardActive'].submit()" <?php echo Mage::getSingleton('giftcards/session')->getActive() ? 'checked="checked"' : '' ?>>
                <label for="giftcard_use"><?php echo $this->__('Use my Gift Card balance.'); ?></label>
            </div>
            </form>
            <form method="post" action="<?php echo $this->getUrl('*/*/giftcardPost'); ?>" id="giftcard-form">
            <label for="giftcard_code"><?php echo $this->__('Or redeem and use your Gift Card now:'); ?></label>
            <div class="input-box">
                <input value="" name="giftcard_code" id="giftcard_code" class="input-text">
            </div>
            <div class="buttons-set">
                <button value="<?php echo $this->__('Redeem and Use') ?>" onclick="giftcardForm.submit(true)" class="button" title="Redeem and Use" type="button"><span><span><?php echo $this->__('Redeem and Use') ?></span></span></button>
            </div>
            </form>
        </div>
        <?php else : ?>
        <div>
            <?php echo $this->__('To use your gift cards, please <a href="%s">register</a> or <a href="%s">log in</a>.', Mage::helper('customer')->getRegisterUrl(), Mage::helper('customer')->getLoginUrl()); ?>
        </div>
        <?php endif; ?>
    </div>
<script type="text/javascript">
//&lt;![CDATA[
var giftcardForm = new VarienForm('giftcard-form');
giftcardForm.submit = function (isRemove) {
    if (isRemove) {
        $('giftcard_code').addClassName('required-entry');
        $('giftcard_use').checked = "checkbox";
        $('giftcard_use').value = "1";
    } else {
        $('giftcard_code').removeClassName('required-entry');
        $('giftcard_use').value = "0";
    }
    return VarienForm.prototype.submit.bind(giftcardForm)();
}
//]]&gt;
</script>