<?php //$_inquiry = $this->getInquiry()  ?>
<script type="text/javascript">
    var offer = new AdminOffer();
</script>
<div class="grid" id="inquiry-items_grid">
    <div class="hor-scroll">
        <table cellspacing="0" class="data order-tables">
            <col />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <thead>
                <tr class="headings">
                    <th><?php echo $this->helper('offer')->__('Product') ?></th>
                    <th><span class="nobr"><?php echo $this->helper('offer')->__('Orginal Price') ?></span></th>
                    <th><span class="nobr"><?php echo $this->helper('offer')->__('Custom Price') ?></span></th>
                    <th class="a-center"><?php echo $this->helper('offer')->__('Qty') ?></th>
                    <th class="last"><span class="nobr"><?php echo $this->helper('offer')->__('Row Total') ?></span></th>
                </tr>
            </thead>
            <?php $_items = $this->getItemsCollection() ?>
            <?php $i = 0;
            foreach ($_items as $_item): ?>
                <?php $i++;
                $product = $_item->getProduct(); ?>
    <?php $_isCustomPrice = $this->usedCustomPriceForItem($_item); ?>
                <tbody class="<?php echo $i % 2 ? 'even' : 'odd' ?>">
                    <tr class="border">
                        <td>
                            <h5 class="title"><?php echo $this->escapeHtml($product->getName()) ?></h5>
                            <div>
                                <strong>SKU:</strong>
    <?php echo $this->escapeHtml($product->getSku()) ?>
                            </div>
                        </td>
                        <td><?php echo Mage::helper('core')->currency($product->getPrice()); ?></td>
                        <td>
                            <input type="checkbox" id="item_use_custom_price_<?php echo $_item->getId() ?>"<?php if ($_isCustomPrice): ?> checked="checked"<?php endif; ?> onclick="offer.toggleCustomPrice(this, 'item_custom_price_<?php echo $_item->getId() ?>', 'item_tier_block_<?php echo $_item->getId() ?>');"/>
                            <input id="item_custom_price_<?php echo $_item->getId() ?>" name="item[<?php echo $_item->getId() ?>][custom_price]" value="<?php echo sprintf("%.2f", $this->getOriginalEditablePrice($_item)) ?>"<?php if (!$_isCustomPrice): ?> style="display:none" disabled="disabled"<?php endif; ?> class="input-text item-price"/>
                        </td>
                        <td><?php echo $_item->getProductQty() ?></td>
                        <td><?php echo Mage::helper('core')->currency($product->getPrice() * $_item->getProductQty()); ?></td>
                    </tr>
                </tbody>
<?php endforeach; ?>
        </table>          
    </div>  
</div>
<table cellspacing="0" width="100%">
    <col width="50%" />
    <col width="50%" />
    <tr>
        <td class="a-left">test</td>
        <td class="a-right"><?php echo $this->getButtonHtml($this->helper('offer')->__('Update Items'), 'offer.itemsUpdate()'); ?></td>
    </tr>
</table>  
<br />