<?php $_inquiryItem = $this->getInquiryItem(); ?>
<?php $_inquirySubmitUrl = $this->helper('offer/inquiry')->getUpdateUrl($_inquiryItem); ?>

<ul class="add-to-links">
<?php if ($this->helper('offer/inquiry')->isAllow()) : ?>
    <li><a href="<?php echo $_inquirySubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, '<?php echo $_inquirySubmitUrl ?>'); return false;" class="link-inquire"><?php echo $this->__('Update Offer Inquiry') ?></a></li>
<?php endif; ?>
<?php $_product = $this->getProduct(); ?>
<?php $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product); ?>
<?php if ($_compareUrl) : ?>
    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
<?php endif; ?>
</ul>
